// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: im.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MSG_TEXT   MsgType = 0
	MsgType_MSG_IMAGE  MsgType = 1
	MsgType_MSG_FILE   MsgType = 2
	MsgType_MSG_AUDIO  MsgType = 3
	MsgType_MSG_VIDEO  MsgType = 4
	MsgType_MSG_CALL   MsgType = 5 // 通话信令封装为会话内消息，便于历史回显
	MsgType_MSG_SYSTEM MsgType = 6
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TEXT",
		1: "MSG_IMAGE",
		2: "MSG_FILE",
		3: "MSG_AUDIO",
		4: "MSG_VIDEO",
		5: "MSG_CALL",
		6: "MSG_SYSTEM",
	}
	MsgType_value = map[string]int32{
		"MSG_TEXT":   0,
		"MSG_IMAGE":  1,
		"MSG_FILE":   2,
		"MSG_AUDIO":  3,
		"MSG_VIDEO":  4,
		"MSG_CALL":   5,
		"MSG_SYSTEM": 6,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

type CallEventType int32

const (
	CallEventType_CALL_INVITE  CallEventType = 0
	CallEventType_CALL_ACCEPT  CallEventType = 1
	CallEventType_CALL_REJECT  CallEventType = 2
	CallEventType_CALL_CANCEL  CallEventType = 3 // 主叫取消
	CallEventType_CALL_HANGUP  CallEventType = 4 // 挂断
	CallEventType_CALL_TIMEOUT CallEventType = 5 // 响铃超时（服务端或被叫产生）
	CallEventType_CALL_BUSY    CallEventType = 6
)

// Enum value maps for CallEventType.
var (
	CallEventType_name = map[int32]string{
		0: "CALL_INVITE",
		1: "CALL_ACCEPT",
		2: "CALL_REJECT",
		3: "CALL_CANCEL",
		4: "CALL_HANGUP",
		5: "CALL_TIMEOUT",
		6: "CALL_BUSY",
	}
	CallEventType_value = map[string]int32{
		"CALL_INVITE":  0,
		"CALL_ACCEPT":  1,
		"CALL_REJECT":  2,
		"CALL_CANCEL":  3,
		"CALL_HANGUP":  4,
		"CALL_TIMEOUT": 5,
		"CALL_BUSY":    6,
	}
)

func (x CallEventType) Enum() *CallEventType {
	p := new(CallEventType)
	*p = x
	return p
}

func (x CallEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[1].Descriptor()
}

func (CallEventType) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[1]
}

func (x CallEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallEventType.Descriptor instead.
func (CallEventType) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_Heartbeat
	//	*Frame_AuthReq
	//	*Frame_AuthResp
	//	*Frame_MsgSend
	//	*Frame_MsgAck
	//	*Frame_MsgNotify
	//	*Frame_MsgPullReq
	//	*Frame_MsgPullResp
	//	*Frame_MsgRead
	//	*Frame_CallSignal
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*Frame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Frame) GetAuthReq() *AuthReq {
	if x != nil {
		if x, ok := x.Body.(*Frame_AuthReq); ok {
			return x.AuthReq
		}
	}
	return nil
}

func (x *Frame) GetAuthResp() *AuthResp {
	if x != nil {
		if x, ok := x.Body.(*Frame_AuthResp); ok {
			return x.AuthResp
		}
	}
	return nil
}

func (x *Frame) GetMsgSend() *MsgSend {
	if x != nil {
		if x, ok := x.Body.(*Frame_MsgSend); ok {
			return x.MsgSend
		}
	}
	return nil
}

func (x *Frame) GetMsgAck() *MsgAck {
	if x != nil {
		if x, ok := x.Body.(*Frame_MsgAck); ok {
			return x.MsgAck
		}
	}
	return nil
}

func (x *Frame) GetMsgNotify() *MsgNotify {
	if x != nil {
		if x, ok := x.Body.(*Frame_MsgNotify); ok {
			return x.MsgNotify
		}
	}
	return nil
}

func (x *Frame) GetMsgPullReq() *MsgPullReq {
	if x != nil {
		if x, ok := x.Body.(*Frame_MsgPullReq); ok {
			return x.MsgPullReq
		}
	}
	return nil
}

func (x *Frame) GetMsgPullResp() *MsgPullResp {
	if x != nil {
		if x, ok := x.Body.(*Frame_MsgPullResp); ok {
			return x.MsgPullResp
		}
	}
	return nil
}

func (x *Frame) GetMsgRead() *MsgRead {
	if x != nil {
		if x, ok := x.Body.(*Frame_MsgRead); ok {
			return x.MsgRead
		}
	}
	return nil
}

func (x *Frame) GetCallSignal() *CallSignal {
	if x != nil {
		if x, ok := x.Body.(*Frame_CallSignal); ok {
			return x.CallSignal
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"` // C<->S 心跳
}

type Frame_AuthReq struct {
	AuthReq *AuthReq `protobuf:"bytes,2,opt,name=auth_req,json=authReq,proto3,oneof"` // C->S 连接后鉴权
}

type Frame_AuthResp struct {
	AuthResp *AuthResp `protobuf:"bytes,3,opt,name=auth_resp,json=authResp,proto3,oneof"` // S->C 鉴权结果
}

type Frame_MsgSend struct {
	MsgSend *MsgSend `protobuf:"bytes,4,opt,name=msg_send,json=msgSend,proto3,oneof"` // C->S 发消息
}

type Frame_MsgAck struct {
	MsgAck *MsgAck `protobuf:"bytes,5,opt,name=msg_ack,json=msgAck,proto3,oneof"` // S->C 发送 ACK（带 seq）/ C->S 收到确认
}

type Frame_MsgNotify struct {
	MsgNotify *MsgNotify `protobuf:"bytes,6,opt,name=msg_notify,json=msgNotify,proto3,oneof"` // S->C 在线投递
}

type Frame_MsgPullReq struct {
	MsgPullReq *MsgPullReq `protobuf:"bytes,7,opt,name=msg_pull_req,json=msgPullReq,proto3,oneof"` // C->S 拉补（离线/重连增量）
}

type Frame_MsgPullResp struct {
	MsgPullResp *MsgPullResp `protobuf:"bytes,8,opt,name=msg_pull_resp,json=msgPullResp,proto3,oneof"` // S->C 拉补结果
}

type Frame_MsgRead struct {
	MsgRead *MsgRead `protobuf:"bytes,9,opt,name=msg_read,json=msgRead,proto3,oneof"` // C->S 已读上报
}

type Frame_CallSignal struct {
	CallSignal *CallSignal `protobuf:"bytes,10,opt,name=call_signal,json=callSignal,proto3,oneof"` // 音视频通话信令（一期走消息通道）
}

func (*Frame_Heartbeat) isFrame_Body() {}

func (*Frame_AuthReq) isFrame_Body() {}

func (*Frame_AuthResp) isFrame_Body() {}

func (*Frame_MsgSend) isFrame_Body() {}

func (*Frame_MsgAck) isFrame_Body() {}

func (*Frame_MsgNotify) isFrame_Body() {}

func (*Frame_MsgPullReq) isFrame_Body() {}

func (*Frame_MsgPullResp) isFrame_Body() {}

func (*Frame_MsgRead) isFrame_Body() {}

func (*Frame_CallSignal) isFrame_Body() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                       // HTTP 登录接口返回的 JWT
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 客户端设备标识
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`                 // android / desktop / web
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{2}
}

func (x *AuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type AuthResp struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ok     bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 鉴权成功后下发服务端最新 seq 概览，客户端可决定是否拉补
	MaxSeqs       map[string]uint64 `protobuf:"bytes,3,rep,name=max_seqs,json=maxSeqs,proto3" json:"max_seqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // conversation_id -> 最新 seq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	mi := &file_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuthResp) GetMaxSeqs() map[string]uint64 {
	if x != nil {
		return x.MaxSeqs
	}
	return nil
}

// 多媒体附件
type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // MinIO 下载地址（预签名）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	Width         uint32                 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"` // 图片/视频
	Height        uint32                 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Duration      uint32                 `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"` // 音视频秒数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{4}
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attachment) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Attachment) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Attachment) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Attachment) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type MsgSend struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId    string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端生成，幂等去重
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MsgType        MsgType                `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3,enum=im.protocol.MsgType" json:"msg_type,omitempty"`
	Text           string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"` // 文本内容 / 通话信令 JSON
	Attachment     *Attachment            `protobuf:"bytes,5,opt,name=attachment,proto3" json:"attachment,omitempty"`
	MentionUids    []string               `protobuf:"bytes,6,rep,name=mention_uids,json=mentionUids,proto3" json:"mention_uids,omitempty"` // 群 @
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgSend) Reset() {
	*x = MsgSend{}
	mi := &file_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSend) ProtoMessage() {}

func (x *MsgSend) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSend.ProtoReflect.Descriptor instead.
func (*MsgSend) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{5}
}

func (x *MsgSend) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MsgSend) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MsgSend) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_TEXT
}

func (x *MsgSend) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MsgSend) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *MsgSend) GetMentionUids() []string {
	if x != nil {
		return x.MentionUids
	}
	return nil
}

type MsgAck struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 发送 ACK 时回显
	Seq         uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                     // 服务端分配的会话内序号
	ServerMsgId string                 `protobuf:"bytes,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"` // 服务端雪花 ID
	// 收到确认（接收方）：确认收到某会话某 seq
	ConversationId string `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgAck) Reset() {
	*x = MsgAck{}
	mi := &file_im_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAck) ProtoMessage() {}

func (x *MsgAck) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAck.ProtoReflect.Descriptor instead.
func (*MsgAck) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{6}
}

func (x *MsgAck) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MsgAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MsgAck) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *MsgAck) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type MsgNotify struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ServerMsgId    string                 `protobuf:"bytes,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	FromUid        string                 `protobuf:"bytes,4,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	MsgType        MsgType                `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3,enum=im.protocol.MsgType" json:"msg_type,omitempty"`
	Text           string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Attachment     *Attachment            `protobuf:"bytes,7,opt,name=attachment,proto3" json:"attachment,omitempty"`
	SentAt         int64                  `protobuf:"varint,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // 毫秒时间戳
	MentionUids    []string               `protobuf:"bytes,9,rep,name=mention_uids,json=mentionUids,proto3" json:"mention_uids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgNotify) Reset() {
	*x = MsgNotify{}
	mi := &file_im_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgNotify) ProtoMessage() {}

func (x *MsgNotify) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgNotify.ProtoReflect.Descriptor instead.
func (*MsgNotify) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{7}
}

func (x *MsgNotify) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MsgNotify) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MsgNotify) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *MsgNotify) GetFromUid() string {
	if x != nil {
		return x.FromUid
	}
	return ""
}

func (x *MsgNotify) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_TEXT
}

func (x *MsgNotify) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MsgNotify) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *MsgNotify) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *MsgNotify) GetMentionUids() []string {
	if x != nil {
		return x.MentionUids
	}
	return nil
}

type MsgPullReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 为空 = 拉全部会话（按 max_seqs 概览逐个补）
	AfterSeq       uint64                 `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`                  // 拉取 > after_seq 的消息
	Limit          uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                        // 单页上限，服务端封顶 200
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgPullReq) Reset() {
	*x = MsgPullReq{}
	mi := &file_im_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPullReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPullReq) ProtoMessage() {}

func (x *MsgPullReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPullReq.ProtoReflect.Descriptor instead.
func (*MsgPullReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{8}
}

func (x *MsgPullReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MsgPullReq) GetAfterSeq() uint64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *MsgPullReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MsgPullResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Msgs           []*MsgNotify           `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	HasMore        bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MaxSeq         uint64                 `protobuf:"varint,4,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"` // 该会话服务端最新 seq
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgPullResp) Reset() {
	*x = MsgPullResp{}
	mi := &file_im_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPullResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPullResp) ProtoMessage() {}

func (x *MsgPullResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPullResp.ProtoReflect.Descriptor instead.
func (*MsgPullResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{9}
}

func (x *MsgPullResp) GetMsgs() []*MsgNotify {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *MsgPullResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *MsgPullResp) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MsgPullResp) GetMaxSeq() uint64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type MsgRead struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UpToSeq        uint64                 `protobuf:"varint,2,opt,name=up_to_seq,json=upToSeq,proto3" json:"up_to_seq,omitempty"` // 已读到此 seq
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgRead) Reset() {
	*x = MsgRead{}
	mi := &file_im_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRead) ProtoMessage() {}

func (x *MsgRead) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRead.ProtoReflect.Descriptor instead.
func (*MsgRead) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{10}
}

func (x *MsgRead) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MsgRead) GetUpToSeq() uint64 {
	if x != nil {
		return x.UpToSeq
	}
	return 0
}

type CallSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // 一次通话唯一 ID（主叫生成）
	Event         CallEventType          `protobuf:"varint,2,opt,name=event,proto3,enum=im.protocol.CallEventType" json:"event,omitempty"`
	RoomName      string                 `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`             // LiveKit room（accept 后主叫/被叫都知道）
	LivekitToken  string                 `protobuf:"bytes,4,opt,name=livekit_token,json=livekitToken,proto3" json:"livekit_token,omitempty"` // 被叫接听时服务端签发的 LiveKit JWT
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`                                     // 附加信息（如拒绝原因）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallSignal) Reset() {
	*x = CallSignal{}
	mi := &file_im_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSignal) ProtoMessage() {}

func (x *CallSignal) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSignal.ProtoReflect.Descriptor instead.
func (*CallSignal) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{11}
}

func (x *CallSignal) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallSignal) GetEvent() CallEventType {
	if x != nil {
		return x.Event
	}
	return CallEventType_CALL_INVITE
}

func (x *CallSignal) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CallSignal) GetLivekitToken() string {
	if x != nil {
		return x.LivekitToken
	}
	return ""
}

func (x *CallSignal) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_im_proto protoreflect.FileDescriptor

const file_im_proto_rawDesc = "" +
	"\n" +
	"\bim.proto\x12\vim.protocol\"\xb8\x04\n" +
	"\x05Frame\x126\n" +
	"\theartbeat\x18\x01 \x01(\v2\x16.im.protocol.HeartbeatH\x00R\theartbeat\x121\n" +
	"\bauth_req\x18\x02 \x01(\v2\x14.im.protocol.AuthReqH\x00R\aauthReq\x124\n" +
	"\tauth_resp\x18\x03 \x01(\v2\x15.im.protocol.AuthRespH\x00R\bauthResp\x121\n" +
	"\bmsg_send\x18\x04 \x01(\v2\x14.im.protocol.MsgSendH\x00R\amsgSend\x12.\n" +
	"\amsg_ack\x18\x05 \x01(\v2\x13.im.protocol.MsgAckH\x00R\x06msgAck\x127\n" +
	"\n" +
	"msg_notify\x18\x06 \x01(\v2\x16.im.protocol.MsgNotifyH\x00R\tmsgNotify\x12;\n" +
	"\fmsg_pull_req\x18\a \x01(\v2\x17.im.protocol.MsgPullReqH\x00R\n" +
	"msgPullReq\x12>\n" +
	"\rmsg_pull_resp\x18\b \x01(\v2\x18.im.protocol.MsgPullRespH\x00R\vmsgPullResp\x121\n" +
	"\bmsg_read\x18\t \x01(\v2\x14.im.protocol.MsgReadH\x00R\amsgRead\x12:\n" +
	"\vcall_signal\x18\n" +
	" \x01(\v2\x17.im.protocol.CallSignalH\x00R\n" +
	"callSignalB\x06\n" +
	"\x04body\"\v\n" +
	"\tHeartbeat\"X\n" +
	"\aAuthReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"\xad\x01\n" +
	"\bAuthResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12=\n" +
	"\bmax_seqs\x18\x03 \x03(\v2\".im.protocol.AuthResp.MaxSeqsEntryR\amaxSeqs\x1a:\n" +
	"\fMaxSeqsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xa4\x01\n" +
	"\n" +
	"Attachment\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x14\n" +
	"\x05width\x18\x05 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\rR\x06height\x12\x1a\n" +
	"\bduration\x18\a \x01(\rR\bduration\"\xf7\x01\n" +
	"\aMsgSend\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12/\n" +
	"\bmsg_type\x18\x03 \x01(\x0e2\x14.im.protocol.MsgTypeR\amsgType\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x127\n" +
	"\n" +
	"attachment\x18\x05 \x01(\v2\x17.im.protocol.AttachmentR\n" +
	"attachment\x12!\n" +
	"\fmention_uids\x18\x06 \x03(\tR\vmentionUids\"\x8b\x01\n" +
	"\x06MsgAck\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\"\n" +
	"\rserver_msg_id\x18\x03 \x01(\tR\vserverMsgId\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\"\xbf\x02\n" +
	"\tMsgNotify\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\"\n" +
	"\rserver_msg_id\x18\x03 \x01(\tR\vserverMsgId\x12\x19\n" +
	"\bfrom_uid\x18\x04 \x01(\tR\afromUid\x12/\n" +
	"\bmsg_type\x18\x05 \x01(\x0e2\x14.im.protocol.MsgTypeR\amsgType\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x127\n" +
	"\n" +
	"attachment\x18\a \x01(\v2\x17.im.protocol.AttachmentR\n" +
	"attachment\x12\x17\n" +
	"\asent_at\x18\b \x01(\x03R\x06sentAt\x12!\n" +
	"\fmention_uids\x18\t \x03(\tR\vmentionUids\"h\n" +
	"\n" +
	"MsgPullReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x04R\bafterSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\x96\x01\n" +
	"\vMsgPullResp\x12*\n" +
	"\x04msgs\x18\x01 \x03(\v2\x16.im.protocol.MsgNotifyR\x04msgs\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x17\n" +
	"\amax_seq\x18\x04 \x01(\x04R\x06maxSeq\"N\n" +
	"\aMsgRead\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1a\n" +
	"\tup_to_seq\x18\x02 \x01(\x04R\aupToSeq\"\xad\x01\n" +
	"\n" +
	"CallSignal\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x120\n" +
	"\x05event\x18\x02 \x01(\x0e2\x1a.im.protocol.CallEventTypeR\x05event\x12\x1b\n" +
	"\troom_name\x18\x03 \x01(\tR\broomName\x12#\n" +
	"\rlivekit_token\x18\x04 \x01(\tR\flivekitToken\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text*p\n" +
	"\aMsgType\x12\f\n" +
	"\bMSG_TEXT\x10\x00\x12\r\n" +
	"\tMSG_IMAGE\x10\x01\x12\f\n" +
	"\bMSG_FILE\x10\x02\x12\r\n" +
	"\tMSG_AUDIO\x10\x03\x12\r\n" +
	"\tMSG_VIDEO\x10\x04\x12\f\n" +
	"\bMSG_CALL\x10\x05\x12\x0e\n" +
	"\n" +
	"MSG_SYSTEM\x10\x06*\x85\x01\n" +
	"\rCallEventType\x12\x0f\n" +
	"\vCALL_INVITE\x10\x00\x12\x0f\n" +
	"\vCALL_ACCEPT\x10\x01\x12\x0f\n" +
	"\vCALL_REJECT\x10\x02\x12\x0f\n" +
	"\vCALL_CANCEL\x10\x03\x12\x0f\n" +
	"\vCALL_HANGUP\x10\x04\x12\x10\n" +
	"\fCALL_TIMEOUT\x10\x05\x12\r\n" +
	"\tCALL_BUSY\x10\x06B\x13Z\x11im/internal/pb;pbb\x06proto3"

var (
	file_im_proto_rawDescOnce sync.Once
	file_im_proto_rawDescData []byte
)

func file_im_proto_rawDescGZIP() []byte {
	file_im_proto_rawDescOnce.Do(func() {
		file_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_proto_rawDesc), len(file_im_proto_rawDesc)))
	})
	return file_im_proto_rawDescData
}

var file_im_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_im_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_im_proto_goTypes = []any{
	(MsgType)(0),        // 0: im.protocol.MsgType
	(CallEventType)(0),  // 1: im.protocol.CallEventType
	(*Frame)(nil),       // 2: im.protocol.Frame
	(*Heartbeat)(nil),   // 3: im.protocol.Heartbeat
	(*AuthReq)(nil),     // 4: im.protocol.AuthReq
	(*AuthResp)(nil),    // 5: im.protocol.AuthResp
	(*Attachment)(nil),  // 6: im.protocol.Attachment
	(*MsgSend)(nil),     // 7: im.protocol.MsgSend
	(*MsgAck)(nil),      // 8: im.protocol.MsgAck
	(*MsgNotify)(nil),   // 9: im.protocol.MsgNotify
	(*MsgPullReq)(nil),  // 10: im.protocol.MsgPullReq
	(*MsgPullResp)(nil), // 11: im.protocol.MsgPullResp
	(*MsgRead)(nil),     // 12: im.protocol.MsgRead
	(*CallSignal)(nil),  // 13: im.protocol.CallSignal
	nil,                 // 14: im.protocol.AuthResp.MaxSeqsEntry
}
var file_im_proto_depIdxs = []int32{
	3,  // 0: im.protocol.Frame.heartbeat:type_name -> im.protocol.Heartbeat
	4,  // 1: im.protocol.Frame.auth_req:type_name -> im.protocol.AuthReq
	5,  // 2: im.protocol.Frame.auth_resp:type_name -> im.protocol.AuthResp
	7,  // 3: im.protocol.Frame.msg_send:type_name -> im.protocol.MsgSend
	8,  // 4: im.protocol.Frame.msg_ack:type_name -> im.protocol.MsgAck
	9,  // 5: im.protocol.Frame.msg_notify:type_name -> im.protocol.MsgNotify
	10, // 6: im.protocol.Frame.msg_pull_req:type_name -> im.protocol.MsgPullReq
	11, // 7: im.protocol.Frame.msg_pull_resp:type_name -> im.protocol.MsgPullResp
	12, // 8: im.protocol.Frame.msg_read:type_name -> im.protocol.MsgRead
	13, // 9: im.protocol.Frame.call_signal:type_name -> im.protocol.CallSignal
	14, // 10: im.protocol.AuthResp.max_seqs:type_name -> im.protocol.AuthResp.MaxSeqsEntry
	0,  // 11: im.protocol.MsgSend.msg_type:type_name -> im.protocol.MsgType
	6,  // 12: im.protocol.MsgSend.attachment:type_name -> im.protocol.Attachment
	0,  // 13: im.protocol.MsgNotify.msg_type:type_name -> im.protocol.MsgType
	6,  // 14: im.protocol.MsgNotify.attachment:type_name -> im.protocol.Attachment
	9,  // 15: im.protocol.MsgPullResp.msgs:type_name -> im.protocol.MsgNotify
	1,  // 16: im.protocol.CallSignal.event:type_name -> im.protocol.CallEventType
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_im_proto_init() }
func file_im_proto_init() {
	if File_im_proto != nil {
		return
	}
	file_im_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Heartbeat)(nil),
		(*Frame_AuthReq)(nil),
		(*Frame_AuthResp)(nil),
		(*Frame_MsgSend)(nil),
		(*Frame_MsgAck)(nil),
		(*Frame_MsgNotify)(nil),
		(*Frame_MsgPullReq)(nil),
		(*Frame_MsgPullResp)(nil),
		(*Frame_MsgRead)(nil),
		(*Frame_CallSignal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_proto_rawDesc), len(file_im_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_im_proto_goTypes,
		DependencyIndexes: file_im_proto_depIdxs,
		EnumInfos:         file_im_proto_enumTypes,
		MessageInfos:      file_im_proto_msgTypes,
	}.Build()
	File_im_proto = out.File
	file_im_proto_goTypes = nil
	file_im_proto_depIdxs = nil
}
